spring:
  datasource:
    url: jdbc:postgresql://${{ secrets.POSTGRES_URL }}:${{ secrets.POSTGRES_PORT }}/${{ secrets.POSTGRES_DATABASE_NAME }}
    username: ${{ secrets.POSTGRES_USER_NAME }}
    password: ${{ secrets.POSTGRES_PASSWORD }}
