# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}  
    
    - name: Pull Image from GitHub Packages
      run: |
        docker pull docker.pkg.github.com/${{ secrets.DOCKERHUB_USERNAME }}/crm-vaadin/crm-vaadin:latest

    
    - name: Build with Gradle
      run: ./gradlew vaadinBuildFrontend build
     
    - name: Build the Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: crm-vaadin
        IMAGE_TAG: crm-vaadin
      run: |
        docker build . --file Dockerfile --tag crm-vaadin:latest
        # docker tag crm-vaadin:latest ${{ secrets.DOCKERHUB_USERNAME }}/crm-vaadin:latest
    
    - name: Tag Image for Docker Hub
      run: |
        docker tag ${{ secrets.DOCKERHUB_USERNAME }}/crm-vaadin:latest crm-vaadin:latest
      
    - name: Push Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/crm-vaadin:latest
