# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}  
    
    - name: Build with Gradle
      run: |
        ./gradlew vaadinBuildFrontend build
      
     
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/crm-vaadin:latest
        
    - name: Stop all containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_ECR_REGISTRY_IP }}
        username: ec2-user  # Change this to your AWS service's SSH username
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        script: |
          docker stop $(docker ps -aq)
    
    - name: Delete all containers
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_ECR_REGISTRY_IP }}
        username: ec2-user  # Change this to your AWS service's SSH username
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        script: |
          docker rm $(docker ps -aq)
          
    - name: Delete all images
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_ECR_REGISTRY_IP }}
        username: ec2-user  # Change this to your AWS service's SSH username
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        script: |
          docker rmi $(docker images -q)
          
    - name: Pull new image from dockerHub
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_ECR_REGISTRY_IP }}
        username: ec2-user  # Change this to your AWS service's SSH username
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        script: |
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/crm-vaadin:latest
          
    - name: Start new container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_ECR_REGISTRY_IP }}
        username: ec2-user  # Change this to your AWS service's SSH username
        key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        script: |
          sudo docker run --env ENV=prod POSTGRES_URL=${{ secrets.POSTGRES_URL }} --env POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} --env POSTGRES_DATABASE_NAME=${{ secrets.POSTGRES_DATABASE_NAME }} --env POSTGRES_USER_NAME=${{ secrets.POSTGRES_USER_NAME }} --env POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} -d -p 80:8080 ${{ secrets.DOCKERHUB_USERNAME }}/crm-vaadin:latest